.TH "RyleRadio.MultiselectDrawer" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.MultiselectDrawer \- Draws the \fBMultiselectAttribute\fP in the inspector\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.RI "Displays the multiselect dropdown\&. "
.in -1c
.SH "Detailed Description"
.PP 
Draws the \fBMultiselectAttribute\fP in the inspector\&. 
.PP
Definition at line \fB130\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RyleRadio\&.MultiselectDrawer\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Displays the multiselect dropdown\&. 
.PP
Definition at line \fB143\fP of file \fBMultiselectAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
