RyleRadio.Editor.RadioInsulatorEditor
NAME
RyleRadio.Editor.RadioInsulatorEditor - Custom inspector for a RadioInsulator
This is mainly so that we can use Handles (draggable gizmos).
SYNOPSIS
Inherits Editor.
Public Member Functions
override void OnInspectorGUI ()
Draw the actual inspector as default.
Private Member Functions
void OnEnable ()
Initializes the insulator's editor.
void OnSceneGUI ()
Displays the handles for RadioInsulator.innerBoxSize and RadioInsulator.outerBoxSize in the scene.
Private Attributes
RadioInsulator insulator = null
The insulator this is linked to.
readonly BoxBoundsHandle outerBoundsHandle = new()
The draggable gizmo for the outer bounds of the insulator.
readonly BoxBoundsHandle innerBoundsHandle = new()
The draggable gizmo for the inner bounds of the insulator.
Detailed Description
Custom inspector for a RadioInsulator
This is mainly so that we can use Handles (draggable gizmos).
See: RadioInsulator
Definition at line 18 of file RadioInsulatorEditor.cs.
Member Function Documentation
void RyleRadio.Editor.RadioInsulatorEditor.OnEnable () [private]
Initializes the insulator's editor.
Definition at line 34 of file RadioInsulatorEditor.cs.
override void RyleRadio.Editor.RadioInsulatorEditor.OnInspectorGUI ()
Draw the actual inspector as default.
Definition at line 93 of file RadioInsulatorEditor.cs.
void RyleRadio.Editor.RadioInsulatorEditor.OnSceneGUI () [private]
Displays the handles for RadioInsulator.innerBoxSize and RadioInsulator.outerBoxSize in the scene.
Definition at line 51 of file RadioInsulatorEditor.cs.
Member Data Documentation
readonly BoxBoundsHandle RyleRadio.Editor.RadioInsulatorEditor.innerBoundsHandle = new() [private]
The draggable gizmo for the inner bounds of the insulator.
Definition at line 28 of file RadioInsulatorEditor.cs.
Referenced by OnEnable(), and OnSceneGUI().
RadioInsulator RyleRadio.Editor.RadioInsulatorEditor.insulator = null [private]
The insulator this is linked to.
Definition at line 23 of file RadioInsulatorEditor.cs.
Referenced by OnEnable(), and OnSceneGUI().
readonly BoxBoundsHandle RyleRadio.Editor.RadioInsulatorEditor.outerBoundsHandle = new() [private]
The draggable gizmo for the outer bounds of the insulator.
Definition at line 26 of file RadioInsulatorEditor.cs.
Referenced by OnEnable(), and OnSceneGUI().
Author
Generated automatically by Doxygen for Ryle Radio from the source code.