.TH "RyleRadio.Components.Base" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Components.Base \- \fBBase\fP interfaces and classes for components, e\&.g: track accessors, output accessors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRadioComponent\fP"
.br
.RI "A scene component that holds a reference to a \fBRadioData\fP\&. "
.ti -1c
.RI "class \fBRadioComponentDataAccessor\fP"
.br
.RI "An extension of \fBRadioComponent\fP that accesses specific tracks on the stored \fBRadioData\fP\&. "
.ti -1c
.RI "class \fBRadioOutputTrackAccessor\fP"
.br
.RI "A sister class to \fBRadioComponent\fP that allows a component to access specific tracks on a \fBRadioOutput\fP in the inspector using an int with a \fBMultiselectAttribute\fP 
.br
\fBSee: \fP\fBRadioInsulator\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBBase\fP interfaces and classes for components, e\&.g: track accessors, output accessors\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
