.TH "RyleRadio.Tracks" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Tracks \- \fBTracks\fP to be used on a radio- includes base classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClipRadioTrack\fP"
.br
.RI "A eventType of \fBRadioTrack\fP that plays from a chosen AudioClip object\&. "
.ti -1c
.RI "interface \fBIRadioTrack\fP"
.br
.RI "Internal interface for a \fBRadioTrack\fP\&. "
.ti -1c
.RI "interface \fBIStationTrack\fP"
.br
.RI "A \fBRadioTrack\fP that can be played as part of a station\&. "
.ti -1c
.RI "class \fBProceduralRadioTrack\fP"
.br
.RI "A \fBRadioTrack\fP that plays procedurally generated audio, such as noice, silence, and waveforms\&. "
.ti -1c
.RI "class \fBRadioTrack\fP"
.br
.RI "A track to play as part of a radio\&. These are the fundamental objects that define the content of the radio, such as clips, procedural audio, stations, and any custom content you create\&. "
.ti -1c
.RI "class \fBRadioTrackPlayer\fP"
.br
.RI "A class that plays a certain \fBRadioTrack\fP at runtime\&. It's created newly for each track on each \fBRadioOutput\fP, and manages the playback entirely\&. "
.ti -1c
.RI "class \fBRadioTrackWrapper\fP"
.br
.RI "A wrapper class for \fBRadioTrack\fP so that track types can be switched between in the inspector! Also contains various values that are track-agnostic\&. "
.ti -1c
.RI "class \fBStationRadioTrack\fP"
.br
.RI "A eventType of \fBRadioTrack\fP that contains other tracks\&. Has a custom editor in \fBStationRadioTrackEditor
.br
\fP This is meant to emulate an actual radio station by storing multiple different tracks and switching between them as it plays\&. It can be used for really any purpose that calls for switching tracks, though- e\&.g: ''''procedural'''' music, complex ambience, easter eggs (kinda) "
.ti -1c
.RI "class \fBStationRadioTrackWrapper\fP"
.br
.RI "A smaller, separate version of \fBRadioTrackWrapper\fP for use in a \fBStationRadioTrack\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTracks\fP to be used on a radio- includes base classes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
