.TH "RyleRadio.Editor.RadioInsulatorEditor" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Editor.RadioInsulatorEditor \- Custom inspector for a \fBRadioInsulator\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.RI "Draw the actual inspector as default\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.RI "Initializes the insulator's editor\&. "
.ti -1c
.RI "void \fBOnSceneGUI\fP ()"
.br
.RI "Displays the handles for \fBRadioInsulator\&.innerBoxSize\fP and \fBRadioInsulator\&.outerBoxSize\fP in the scene\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRadioInsulator\fP \fBinsulator\fP = null"
.br
.RI "The insulator this is linked to\&. "
.ti -1c
.RI "readonly BoxBoundsHandle \fBouterBoundsHandle\fP = new()"
.br
.RI "The draggable gizmo for the outer bounds of the insulator\&. "
.ti -1c
.RI "readonly BoxBoundsHandle \fBinnerBoundsHandle\fP = new()"
.br
.RI "The draggable gizmo for the inner bounds of the insulator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Custom inspector for a \fBRadioInsulator\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&. 

\fBSee: \fP \fBRadioInsulator\fP 
.PP
Definition at line \fB18\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RyleRadio\&.Editor\&.RadioInsulatorEditor\&.OnEnable ()\fR [private]\fP"

.PP
Initializes the insulator's editor\&. 
.PP
Definition at line \fB34\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.SS "override void RyleRadio\&.Editor\&.RadioInsulatorEditor\&.OnInspectorGUI ()"

.PP
Draw the actual inspector as default\&. 
.PP
Definition at line \fB93\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.SS "void RyleRadio\&.Editor\&.RadioInsulatorEditor\&.OnSceneGUI ()\fR [private]\fP"

.PP
Displays the handles for \fBRadioInsulator\&.innerBoxSize\fP and \fBRadioInsulator\&.outerBoxSize\fP in the scene\&. 
.PP
Definition at line \fB51\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly BoxBoundsHandle RyleRadio\&.Editor\&.RadioInsulatorEditor\&.innerBoundsHandle = new()\fR [private]\fP"

.PP
The draggable gizmo for the inner bounds of the insulator\&. 
.PP
Definition at line \fB28\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.
.SS "\fBRadioInsulator\fP RyleRadio\&.Editor\&.RadioInsulatorEditor\&.insulator = null\fR [private]\fP"

.PP
The insulator this is linked to\&. 
.PP
Definition at line \fB23\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.
.SS "readonly BoxBoundsHandle RyleRadio\&.Editor\&.RadioInsulatorEditor\&.outerBoundsHandle = new()\fR [private]\fP"

.PP
The draggable gizmo for the outer bounds of the insulator\&. 
.PP
Definition at line \fB26\fP of file \fBRadioInsulatorEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
