RyleRadio.Components.Base.RadioOutputTrackAccessor
NAME
RyleRadio.Components.Base.RadioOutputTrackAccessor - A sister class to RadioComponent that allows a component to access specific tracks on a RadioOutput in the inspector using an int with a MultiselectAttribute
See: RadioInsulator.
SYNOPSIS
Inherits MonoBehaviour.
Inherited by RyleRadio.Components.RadioInteractor.
Protected Member Functions
void DoTrackAction (int _trackMask, Action< string > _action)
Performs an action on any selected tracks using a MultiselectAttribute.
Protected Attributes
RadioOutput output
The RadioOutput to get tracks from.
Properties
List< string > TrackNames [get]
The names of tracks available in the Output.
Detailed Description
A sister class to RadioComponent that allows a component to access specific tracks on a RadioOutput in the inspector using an int with a MultiselectAttribute
See: RadioInsulator.
Definition at line 11 of file RadioOutputTrackAccessor.cs.
Member Function Documentation
void RyleRadio.Components.Base.RadioOutputTrackAccessor.DoTrackAction (int _trackMask, Action< string > _action) [protected]
Performs an action on any selected tracks using a MultiselectAttribute.
Parameters
_trackMask The int with the MultiselectAttribute that the player uses to select tracks from the Output
_action The action to perform on the tracks
Definition at line 30 of file RadioOutputTrackAccessor.cs.
Referenced by RyleRadio.Components.RadioInteractor.FlipPause(), RyleRadio.Components.RadioInteractor.Pause(), RyleRadio.Components.RadioInteractor.PlayLoop(), RyleRadio.Components.RadioInteractor.PlayOneShot(), RyleRadio.Components.RadioInteractor.ResetProgress(), RyleRadio.Components.RadioInteractor.Stop(), and RyleRadio.Components.RadioInteractor.Unpause().
Member Data Documentation
RadioOutput RyleRadio.Components.Base.RadioOutputTrackAccessor.output [protected]
The RadioOutput to get tracks from.
Definition at line 16 of file RadioOutputTrackAccessor.cs.
Referenced by DoTrackAction(), RyleRadio.Components.RadioInteractor.FlipPause(), RyleRadio.Components.RadioInteractor.Pause(), RyleRadio.Components.RadioInteractor.PlayLoop(), RyleRadio.Components.RadioInteractor.PlayOneShot(), RyleRadio.Components.RadioInteractor.ResetProgress(), RyleRadio.Components.RadioInteractor.Stop(), and RyleRadio.Components.RadioInteractor.Unpause().
Property Documentation
List<string> RyleRadio.Components.Base.RadioOutputTrackAccessor.TrackNames [get], [protected]
The names of tracks available in the Output.
Definition at line 21 of file RadioOutputTrackAccessor.cs.
Author
Generated automatically by Doxygen for Ryle Radio from the source code.