.TH "RyleRadio.Components.Base.RadioOutputTrackAccessor" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Components.Base.RadioOutputTrackAccessor \- A sister class to \fBRadioComponent\fP that allows a component to access specific tracks on a \fBRadioOutput\fP in the inspector using an int with a \fBMultiselectAttribute\fP 
.br
\fBSee: \fP\fBRadioInsulator\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBRyleRadio\&.Components\&.RadioInteractor\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDoTrackAction\fP (int _trackMask, Action< string > _action)"
.br
.RI "Performs an action on any selected tracks using a \fBMultiselectAttribute\fP\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRadioOutput\fP \fBoutput\fP"
.br
.RI "The \fBRadioOutput\fP to get tracks from\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< string > \fBTrackNames\fP\fR [get]\fP"
.br
.RI "The names of tracks available in the Output\&. "
.in -1c
.SH "Detailed Description"
.PP 
A sister class to \fBRadioComponent\fP that allows a component to access specific tracks on a \fBRadioOutput\fP in the inspector using an int with a \fBMultiselectAttribute\fP 
.br
\fBSee: \fP\fBRadioInsulator\fP\&. 
.PP
Definition at line \fB11\fP of file \fBRadioOutputTrackAccessor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RyleRadio\&.Components\&.Base\&.RadioOutputTrackAccessor\&.DoTrackAction (int _trackMask, Action< string > _action)\fR [protected]\fP"

.PP
Performs an action on any selected tracks using a \fBMultiselectAttribute\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fI_trackMask\fP The int with the \fBMultiselectAttribute\fP that the player uses to select tracks from the Output
.br
\fI_action\fP The action to perform on the tracks
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBRadioOutputTrackAccessor\&.cs\fP\&.
.PP
Referenced by \fBRyleRadio\&.Components\&.RadioInteractor\&.FlipPause()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.Pause()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.PlayLoop()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.PlayOneShot()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.ResetProgress()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.Stop()\fP, and \fBRyleRadio\&.Components\&.RadioInteractor\&.Unpause()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRadioOutput\fP RyleRadio\&.Components\&.Base\&.RadioOutputTrackAccessor\&.output\fR [protected]\fP"

.PP
The \fBRadioOutput\fP to get tracks from\&. 
.PP
Definition at line \fB16\fP of file \fBRadioOutputTrackAccessor\&.cs\fP\&.
.PP
Referenced by \fBDoTrackAction()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.FlipPause()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.Pause()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.PlayLoop()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.PlayOneShot()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.ResetProgress()\fP, \fBRyleRadio\&.Components\&.RadioInteractor\&.Stop()\fP, and \fBRyleRadio\&.Components\&.RadioInteractor\&.Unpause()\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<string> RyleRadio\&.Components\&.Base\&.RadioOutputTrackAccessor\&.TrackNames\fR [get]\fP, \fR [protected]\fP"

.PP
The names of tracks available in the Output\&. 
.PP
Definition at line \fB21\fP of file \fBRadioOutputTrackAccessor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
