.TH "RyleRadio.Tracks.IStationTrack" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Tracks.IStationTrack \- A \fBRadioTrack\fP that can be played as part of a station\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.PP
Inherited by \fBRyleRadio\&.Tracks\&.ClipRadioTrack\fP, and \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsInStation\fP\fR [get, set]\fP"
.br
.RI "Whether or not this track is part of a station\&. "
.in -1c

Properties inherited from \fBRyleRadio\&.Tracks\&.IRadioTrack\fP
.in +1c
.ti -1c
.RI "float \fBSampleRate\fP\fR [get, set]\fP"
.br
.RI "The samples per second of this track right now\&. Can be changed at runtime, e\&.g: \fBStationRadioTrack\fP\&. "
.ti -1c
.RI "int \fBSampleCount\fP\fR [get, set]\fP"
.br
.RI "The total number of samples in this track right now\&. Can be changed at runtime, e\&.g: \fBStationRadioTrack\fP\&. "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBRyleRadio\&.Tracks\&.IRadioTrack\fP
.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.RI "Initializes this track\&. "
.ti -1c
.RI "float \fBGetSample\fP (int _sampleIndex)"
.br
.RI "Get a sample at the provided index\&. This is the core method of a track- whatever you return here defines the audio that the track will play when selected\&. "
.ti -1c
.RI "virtual void \fBAddToPlayerEndCallback\fP (ref Action< \fBRadioTrackPlayer\fP > _callback)"
.br
.RI "Update a \fBRadioTrackPlayer\fP when this current track ends\&. Used in \fBStationRadioTrack\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
A \fBRadioTrack\fP that can be played as part of a station\&. 

This may end up being useless in future if all tracks can be used as part of a station- currently only other \fBStationRadioTrack\fP s don't have this (so you can't nest stations) but that could be changed in future\&.

.PP
.PP
.nf
public class MyCustomTrack : RadioTrack, IStationTrack { \&.\&.\&. }
.fi
.PP

.PP
Definition at line \fB10\fP of file \fBIStationTrack\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool RyleRadio\&.Tracks\&.IStationTrack\&.IsInStation\fR [get]\fP, \fR [set]\fP"

.PP
Whether or not this track is part of a station\&. 
.PP
Implemented in \fBRyleRadio\&.Tracks\&.ClipRadioTrack\fP, and \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\fP\&.
.PP
Definition at line \fB15\fP of file \fBIStationTrack\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
