RyleRadio.Components.Base.RadioComponentDataAccessor
NAME
RyleRadio.Components.Base.RadioComponentDataAccessor - An extension of RadioComponent that accesses specific tracks on the stored RadioData.
SYNOPSIS
Inherits RyleRadio.Components.Base.RadioComponent.
Inherited by RyleRadio.Components.RadioBroadcaster, and RyleRadio.Components.RadioInsulator.
Public Member Functions
override void Init ()
Initialises this component and links its affected tracks.
Public Member Functions inherited from RyleRadio.Components.Base.RadioComponent
void Init ()
Initialises this component.
Protected Member Functions
void AssignToTrack (RadioTrackWrapper _track)
Links this component to a track.
void RemoveFromTrack (RadioTrackWrapper _track)
Unlinks this component from a track.
virtual void AccessorInit ()
Allows extra code for initialization so that Init() can still be called.
Properties
List< string > TrackNames [get]
The list of tracks on the RadioData that this component can choose from.
Action< RadioComponent > OnInit = new(_ => { }) [get, set]
Event called when the component is initialized.
Properties inherited from RyleRadio.Components.Base.RadioComponent
RadioData Data [get]
Read-only accessor for data.
Private Member Functions
void AssignToTracksGeneric ()
Generally applicable method that converts affectedTracks to a list of tracks, then calls AssignToTrack() to link this component to each of them.
Private Attributes
int affectedTracks
The tracks that this component affects. This is displayed with a MultiselectAttribute.
int lastAffectedTracks
The tracks that were affected previously- only matters if affected tracks are changed at runtime (which currently is not possible)
Additional Inherited Members
Protected Attributes inherited from RyleRadio.Components.Base.RadioComponent
RadioData data
The RadioData (aka just radio) that this component is linked to.
Detailed Description
An extension of RadioComponent that accesses specific tracks on the stored RadioData.
Definition at line 12 of file RadioComponentDataAccessor.cs.
Member Function Documentation
virtual void RyleRadio.Components.Base.RadioComponentDataAccessor.AccessorInit () [protected], [virtual]
Allows extra code for initialization so that Init() can still be called.
Definition at line 98 of file RadioComponentDataAccessor.cs.
Referenced by Init().
void RyleRadio.Components.Base.RadioComponentDataAccessor.AssignToTracksGeneric () [private]
Generally applicable method that converts affectedTracks to a list of tracks, then calls AssignToTrack() to link this component to each of them.
Definition at line 54 of file RadioComponentDataAccessor.cs.
Referenced by Init().
override void RyleRadio.Components.Base.RadioComponentDataAccessor.Init ()
Initialises this component and links its affected tracks.
Definition at line 41 of file RadioComponentDataAccessor.cs.
Member Data Documentation
int RyleRadio.Components.Base.RadioComponentDataAccessor.affectedTracks [private]
The tracks that this component affects. This is displayed with a MultiselectAttribute.
Definition at line 18 of file RadioComponentDataAccessor.cs.
Referenced by AssignToTracksGeneric().
int RyleRadio.Components.Base.RadioComponentDataAccessor.lastAffectedTracks [private]
The tracks that were affected previously- only matters if affected tracks are changed at runtime (which currently is not possible)
Definition at line 23 of file RadioComponentDataAccessor.cs.
Referenced by AssignToTracksGeneric().
Property Documentation
Action<RadioComponent> RyleRadio.Components.Base.RadioComponentDataAccessor.OnInit = new(_ => { }) [get], [set]
Event called when the component is initialized.
Definition at line 35 of file RadioComponentDataAccessor.cs.
Referenced by Init().
List<string> RyleRadio.Components.Base.RadioComponentDataAccessor.TrackNames [get], [protected]
The list of tracks on the RadioData that this component can choose from.
Definition at line 28 of file RadioComponentDataAccessor.cs.
Author
Generated automatically by Doxygen for Ryle Radio from the source code.