.TH "RyleRadio.Editor.RadioBroadcasterEditor" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Editor.RadioBroadcasterEditor \- Custom inspector for a \fBRadioBroadcaster\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.RI "Draw the actual inspector as default\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.RI "Initializes the broadcaster's editor\&. "
.ti -1c
.RI "void \fBOnSceneGUI\fP ()"
.br
.RI "Displays the handles for \fBRadioBroadcaster\&.broadcastRadius\fP in the scene\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRadioBroadcaster\fP \fBbroadcaster\fP"
.br
.RI "The broadcaster this is linked to\&. "
.ti -1c
.RI "Color \fBinnerColor\fP"
.br
.RI "The colour of the gizmo for the x/inner value of \fBRadioBroadcaster\&.broadcastRadius\fP\&. "
.ti -1c
.RI "Color \fBouterColor\fP"
.br
.RI "The colour of the gizmo for the y/outer value of \fBRadioBroadcaster\&.broadcastRadius\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Custom inspector for a \fBRadioBroadcaster\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&. 

\fBSee: \fP \fBRadioBroadcaster\fP 
.PP
Definition at line \fB17\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.OnEnable ()\fR [private]\fP"

.PP
Initializes the broadcaster's editor\&. 
.PP
Definition at line \fB33\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.SS "override void RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.OnInspectorGUI ()"

.PP
Draw the actual inspector as default\&. 
.PP
Definition at line \fB76\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.SS "void RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.OnSceneGUI ()\fR [private]\fP"

.PP
Displays the handles for \fBRadioBroadcaster\&.broadcastRadius\fP in the scene\&. 
.PP
Definition at line \fB56\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRadioBroadcaster\fP RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.broadcaster\fR [private]\fP"

.PP
The broadcaster this is linked to\&. 
.PP
Definition at line \fB22\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.
.SS "Color RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.innerColor\fR [private]\fP"

.PP
The colour of the gizmo for the x/inner value of \fBRadioBroadcaster\&.broadcastRadius\fP\&. 
.PP
Definition at line \fB25\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.
.SS "Color RyleRadio\&.Editor\&.RadioBroadcasterEditor\&.outerColor\fR [private]\fP"

.PP
The colour of the gizmo for the y/outer value of \fBRadioBroadcaster\&.broadcastRadius\fP\&. 
.PP
Definition at line \fB27\fP of file \fBRadioBroadcasterEditor\&.cs\fP\&.
.PP
Referenced by \fBOnEnable()\fP, and \fBOnSceneGUI()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
