.TH "RyleRadio.Components.RadioInsulator" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Components.RadioInsulator \- An "insulator" for a \fBRadioTrackWrapper\fP - if a \fBRadioOutput\fP is inside the bounds of this object, the affected tracks on it will become quieter\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRyleRadio\&.Components\&.Base\&.RadioComponentDataAccessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetPower\fP (Vector3 _position)"
.br
.RI "Gets the power of this insulator at a specific position\&. "
.in -1c

Public Member Functions inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponentDataAccessor\fP
.in +1c
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.RI "Initialises this component and links its affected tracks\&. "
.in -1c

Public Member Functions inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponent\fP
.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.RI "Initialises this component\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBinnerBoxSize\fP = Vector3\&.one * 0\&.9f"
.br
.RI "The size of the inner box of the insulator- inside of this box, insulation is the highest\&. "
.ti -1c
.RI "Vector3 \fBouterBoxSize\fP = Vector3\&.one"
.br
.RI "The size of the outer box of the insulator- outside of this box, insulation is 0- between this and the inner box, insulation is between [0 - 1]\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAssignToTrack\fP (\fBRadioTrackWrapper\fP _track)"
.br
.RI "Links this insulator to a track\&. "
.ti -1c
.RI "override void \fBRemoveFromTrack\fP (\fBRadioTrackWrapper\fP _track)"
.br
.RI "Unlinks this insulator from a track\&. "
.in -1c

Protected Member Functions inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponentDataAccessor\fP
.in +1c
.ti -1c
.RI "void \fBAssignToTrack\fP (\fBRadioTrackWrapper\fP _track)"
.br
.RI "Links this component to a track\&. "
.ti -1c
.RI "void \fBRemoveFromTrack\fP (\fBRadioTrackWrapper\fP _track)"
.br
.RI "Unlinks this component from a track\&. "
.ti -1c
.RI "virtual void \fBAccessorInit\fP ()"
.br
.RI "Allows extra code for initialization so that \fBInit()\fP can still be called\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Vector3 \fBInnerBoxSizeAdjusted\fP\fR [get, private set]\fP"
.br
.RI "The \fBinnerBoxSize\fP but adjusted with \fRtransform\&.localScale\fP in \fBUpdate()\fP "
.ti -1c
.RI "Vector3 \fBOuterBoxSizeAdjusted\fP\fR [get, private set]\fP"
.br
.RI "The \fBouterBoxSize\fP but adjusted with \fRtransform\&.localScale\fP in \fBUpdate()\fP "
.ti -1c
.RI "bool \fBShowApplyToAllOutputs\fP\fR [get]\fP"
.br
.RI "Shows \fBapplyToAllOutputsOutside\fP when the x-value of \fBinsulation\fP is greater than 0\&. "
.in -1c

Properties inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponentDataAccessor\fP
.in +1c
.ti -1c
.RI "List< string > \fBTrackNames\fP\fR [get]\fP"
.br
.RI "The list of tracks on the \fBRadioData\fP that this component can choose from\&. "
.ti -1c
.RI "Action< \fBRadioComponent\fP > \fBOnInit\fP = new(_ => { })\fR [get, set]\fP"
.br
.RI "Event called when the component is initialized\&. "
.in -1c

Properties inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponent\fP
.in +1c
.ti -1c
.RI "\fBRadioData\fP \fBData\fP\fR [get]\fP"
.br
.RI "Read-only accessor for \fBdata\fP\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Updates cached position and adjusted box sizes\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBinsulation\fP = new(0, 0\&.5f)"
.br
.RI "The max and min insulation in the outer and inner boxes\&. "
.ti -1c
.RI "AnimationCurve \fBinsulationCurve\fP = AnimationCurve\&.Linear(0, 0, 1, 1)"
.br
.RI "A curve that defines insulation between the inner and outer boxes- the x-value is how far between the inner and outer boxes the output is\&. "
.ti -1c
.RI "bool \fBapplyToAllOutputsOutside\fP = false"
.br
.RI "Effectively makes this insulator global- when this is true, any output outside of the outer box's range will be affected by the x-value on \fBinsulation\fP\&. "
.ti -1c
.RI "Vector3 \fBcachedPos\fP"
.br
.RI "The position of the insulator in the previous frame\&. We cannot access transform\&.position in the audio thread, so we cache it to this\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBRyleRadio\&.Components\&.Base\&.RadioComponent\fP
.in +1c
.ti -1c
.RI "\fBRadioData\fP \fBdata\fP"
.br
.RI "The \fBRadioData\fP (aka just radio) that this component is linked to\&. "
.in -1c
.SH "Detailed Description"
.PP 
An "insulator" for a \fBRadioTrackWrapper\fP - if a \fBRadioOutput\fP is inside the bounds of this object, the affected tracks on it will become quieter\&. 

There aren't really any real-world analogues for the strength of an insulator like this- think of it like putting a radio in a Faraday cage or something I suppose

.PP
This also has custom editor stuff in \fBRadioInsulatorEditor\fP 
.PP
Definition at line \fB17\fP of file \fBRadioInsulator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RyleRadio\&.Components\&.RadioInsulator\&.AssignToTrack (\fBRadioTrackWrapper\fP _track)\fR [protected]\fP"

.PP
Links this insulator to a track\&. 
.PP
\fBParameters\fP
.RS 4
\fI_track\fP The track to link to
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBRadioInsulator\&.cs\fP\&.
.SS "float RyleRadio\&.Components\&.RadioInsulator\&.GetPower (Vector3 _position)"

.PP
Gets the power of this insulator at a specific position\&. 
.PP
\fBParameters\fP
.RS 4
\fI_position\fP The position to evaluate with
.RE
.PP
\fBReturns\fP
.RS 4
The insulation multiplier at the position\&. The lower the number, the stronger the insulation- it's a multiplier intended to shrink the samples rather than grow them
.RE
.PP

.PP
Definition at line \fB112\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBRyleRadio\&.Tracks\&.RadioTrackPlayer\&.GetInsulation()\fP\&.
.SS "override void RyleRadio\&.Components\&.RadioInsulator\&.RemoveFromTrack (\fBRadioTrackWrapper\fP _track)\fR [protected]\fP"

.PP
Unlinks this insulator from a track\&. 
.PP
\fBParameters\fP
.RS 4
\fI_track\fP The track to unlink from
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBRadioInsulator\&.cs\fP\&.
.SS "void RyleRadio\&.Components\&.RadioInsulator\&.Update ()\fR [private]\fP"

.PP
Updates cached position and adjusted box sizes\&. 
.PP
Definition at line \fB77\fP of file \fBRadioInsulator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool RyleRadio\&.Components\&.RadioInsulator\&.applyToAllOutputsOutside = false\fR [private]\fP"

.PP
Effectively makes this insulator global- when this is true, any output outside of the outer box's range will be affected by the x-value on \fBinsulation\fP\&. This only shows when the x-value of insulation is above 0 
.PP
Definition at line \fB55\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP\&.
.SS "Vector3 RyleRadio\&.Components\&.RadioInsulator\&.cachedPos\fR [private]\fP"

.PP
The position of the insulator in the previous frame\&. We cannot access transform\&.position in the audio thread, so we cache it to this\&. 
.PP
Definition at line \fB60\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP, and \fBUpdate()\fP\&.
.SS "Vector3 RyleRadio\&.Components\&.RadioInsulator\&.innerBoxSize = Vector3\&.one * 0\&.9f"

.PP
The size of the inner box of the insulator- inside of this box, insulation is the highest\&. 
.PP
Definition at line \fB23\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBUpdate()\fP\&.
.SS "Vector2 RyleRadio\&.Components\&.RadioInsulator\&.insulation = new(0, 0\&.5f)\fR [private]\fP"

.PP
The max and min insulation in the outer and inner boxes\&. If an output is on the edge of the outer box, insulation will be the x-value here\&. If an output is inside the inner box, insulation will be the y-value\&. If an output is between the inner and outer boxes, it will be somewhere between the x and y values according to the \fBinsulationCurve\fP

.PP
If the x-value is above 0, you might want to toggle \fBapplyToAllOutputsOutside\fP so this becomes global 
.PP
Definition at line \fB41\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP\&.
.SS "AnimationCurve RyleRadio\&.Components\&.RadioInsulator\&.insulationCurve = AnimationCurve\&.Linear(0, 0, 1, 1)\fR [private]\fP"

.PP
A curve that defines insulation between the inner and outer boxes- the x-value is how far between the inner and outer boxes the output is\&. 
.PP
Definition at line \fB47\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP\&.
.SS "Vector3 RyleRadio\&.Components\&.RadioInsulator\&.outerBoxSize = Vector3\&.one"

.PP
The size of the outer box of the insulator- outside of this box, insulation is 0- between this and the inner box, insulation is between [0 - 1]\&. 
.PP
Definition at line \fB28\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBUpdate()\fP\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 RyleRadio\&.Components\&.RadioInsulator\&.InnerBoxSizeAdjusted\fR [get]\fP, \fR [private set]\fP"

.PP
The \fBinnerBoxSize\fP but adjusted with \fRtransform\&.localScale\fP in \fBUpdate()\fP 
.PP
Definition at line \fB64\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP, and \fBUpdate()\fP\&.
.SS "Vector3 RyleRadio\&.Components\&.RadioInsulator\&.OuterBoxSizeAdjusted\fR [get]\fP, \fR [private set]\fP"

.PP
The \fBouterBoxSize\fP but adjusted with \fRtransform\&.localScale\fP in \fBUpdate()\fP 
.PP
Definition at line \fB66\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP, and \fBUpdate()\fP\&.
.SS "bool RyleRadio\&.Components\&.RadioInsulator\&.ShowApplyToAllOutputs\fR [get]\fP, \fR [private]\fP"

.PP
Shows \fBapplyToAllOutputsOutside\fP when the x-value of \fBinsulation\fP is greater than 0\&. 
.PP
Definition at line \fB71\fP of file \fBRadioInsulator\&.cs\fP\&.
.PP
Referenced by \fBGetPower()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
