.TH "RyleRadio.Editor.StationRadioTrackEditor" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Editor.StationRadioTrackEditor \- The editor for a \fBStationRadioTrack\fP 
.br

.br
This mainly exists so that we can reset any newly added tracks in the station- much the same as \fBRadioDataEditor\fP 
.br
\fBSee: \fP\fBStationRadioTrack\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGUI\fP (Rect _position, SerializedProperty _property, GUIContent _label)"
.br
.RI "Draws the track, its child tracks, and other variables, e\&.g: randomisation settings\&. "
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.RI "Gets the total height of this track in the inspector, including child tracks\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlastTrackWSize\fP = \-1"
.br
.RI "The last recorded number of tracks in this station\&. "
.ti -1c
.RI "bool \fBisShowingThreshold\fP = false"
.br
.RI "Whether or not the random threshold is currently visible in the inspector\&. "
.ti -1c
.RI "bool \fBshowTrackInParent\fP = true"
.br
.RI "Whether or not this track is showing its child tracks- optional variable for cleanliness\&. "
.in -1c
.SH "Detailed Description"
.PP 
The editor for a \fBStationRadioTrack\fP 
.br

.br
This mainly exists so that we can reset any newly added tracks in the station- much the same as \fBRadioDataEditor\fP 
.br
\fBSee: \fP\fBStationRadioTrack\fP\&. 
.PP
Definition at line \fB16\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override float RyleRadio\&.Editor\&.StationRadioTrackEditor\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Gets the total height of this track in the inspector, including child tracks\&. 
.PP
Definition at line \fB143\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.SS "override void RyleRadio\&.Editor\&.StationRadioTrackEditor\&.OnGUI (Rect _position, SerializedProperty _property, GUIContent _label)"

.PP
Draws the track, its child tracks, and other variables, e\&.g: randomisation settings\&. 
.PP
Definition at line \fB30\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool RyleRadio\&.Editor\&.StationRadioTrackEditor\&.isShowingThreshold = false\fR [private]\fP"

.PP
Whether or not the random threshold is currently visible in the inspector\&. 
.PP
Definition at line \fB22\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.PP
Referenced by \fBGetPropertyHeight()\fP, and \fBOnGUI()\fP\&.
.SS "int RyleRadio\&.Editor\&.StationRadioTrackEditor\&.lastTrackWSize = \-1\fR [private]\fP"

.PP
The last recorded number of tracks in this station\&. 
.PP
Definition at line \fB19\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.PP
Referenced by \fBOnGUI()\fP\&.
.SS "bool RyleRadio\&.Editor\&.StationRadioTrackEditor\&.showTrackInParent = true\fR [private]\fP"

.PP
Whether or not this track is showing its child tracks- optional variable for cleanliness\&. 
.PP
Definition at line \fB25\fP of file \fBStationRadioTrackEditor\&.cs\fP\&.
.PP
Referenced by \fBGetPropertyHeight()\fP, and \fBOnGUI()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
