.TH "RyleRadio.Tracks.RadioTrack" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Tracks.RadioTrack \- A track to play as part of a radio\&. These are the fundamental objects that define the content of the radio, such as clips, procedural audio, stations, and any custom content you create\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.PP
Inherited by \fBRyleRadio\&.Tracks\&.ClipRadioTrack\fP, \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\fP, and \fBRyleRadio\&.Tracks\&.StationRadioTrack\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.RI "Initializes this track\&. "
.ti -1c
.RI "float \fBGetSample\fP (int _sampleIndex)"
.br
.RI "Gets a sample from the track\&. "
.ti -1c
.RI "virtual void \fBAddToPlayerEndCallback\fP (ref Action< \fBRadioTrackPlayer\fP > _callback)"
.br
.RI "Activates an event to run whenever this track ends\&. This is mainly used for stations to switch track when the previous one ends\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBSampleRate\fP\fR [get, set]\fP"
.br
.RI "The sample rate of this track\&. "
.ti -1c
.RI "virtual int \fBSampleCount\fP\fR [get, set]\fP"
.br
.RI "The number of samples in this track\&. "
.in -1c
.SH "Detailed Description"
.PP 
A track to play as part of a radio\&. These are the fundamental objects that define the content of the radio, such as clips, procedural audio, stations, and any custom content you create\&. 

\fBIRadioTrack\fP 

.PP
\fBNOTE FOR CUSTOM TRACK CREATORS!!\fP

.PP
!!! IMPORTANT NOTE - if you're creating a custom \fBRadioTrack\fP, you need to both inherit from this class AND have a const string named \fRDISPLAY_NAME\fP\&. Because the version of c# unity uses does not support static virtual data, we have no way of enforcing that you do this- but you will get errors otherwise It's necessary for wrappers when they're listing each available track eventType in a dropdown- NaughtyAttributes' reflection system is used to pull the display id so that it's selectable in the inspector\&. the only downside is a lack of enforcement :((( 
.PP
Definition at line \fB19\fP of file \fBRadioTrack\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void RyleRadio\&.Tracks\&.RadioTrack\&.AddToPlayerEndCallback (ref Action< \fBRadioTrackPlayer\fP > _callback)\fR [virtual]\fP"

.PP
Activates an event to run whenever this track ends\&. This is mainly used for stations to switch track when the previous one ends\&. 
.PP
\fBParameters\fP
.RS 4
\fI_callback\fP A function to run when this track ends
.RE
.PP

.PP
Implements \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.PP
Reimplemented in \fBRyleRadio\&.Tracks\&.StationRadioTrack\fP\&.
.PP
Definition at line \fB53\fP of file \fBRadioTrack\&.cs\fP\&.
.SS "float RyleRadio\&.Tracks\&.RadioTrack\&.GetSample (int _sampleIndex)\fR [abstract]\fP"

.PP
Gets a sample from the track\&. 
.PP
\fBParameters\fP
.RS 4
\fI_sampleIndex\fP The index of the sample to retrieve
.RE
.PP
\fBReturns\fP
.RS 4
The height of the sample
.RE
.PP
\fBIRadioTrack\&.GetSample(int)\fP 
.PP
Implements \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.SS "void RyleRadio\&.Tracks\&.RadioTrack\&.Init ()\fR [abstract]\fP"

.PP
Initializes this track\&. \fBIRadioTrack\&.Init\fP 
.PP
Implements \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual int RyleRadio\&.Tracks\&.RadioTrack\&.SampleCount\fR [get]\fP, \fR [set]\fP"

.PP
The number of samples in this track\&. \fBIRadioTrack\&.SampleCount\fP 
.PP
Implements \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.PP
Definition at line \fB33\fP of file \fBRadioTrack\&.cs\fP\&.
.PP
Referenced by \fBRyleRadio\&.Tracks\&.ClipRadioTrack\&.Init()\fP, \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\&.Init()\fP, and \fBRyleRadio\&.Tracks\&.StationRadioTrack\&.NextTrack()\fP\&.
.SS "float RyleRadio\&.Tracks\&.RadioTrack\&.SampleRate\fR [get]\fP, \fR [set]\fP"

.PP
The sample rate of this track\&. \fBIRadioTrack\&.SampleRate\fP 
.PP
Implements \fBRyleRadio\&.Tracks\&.IRadioTrack\fP\&.
.PP
Definition at line \fB27\fP of file \fBRadioTrack\&.cs\fP\&.
.PP
Referenced by \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\&.GetSample()\fP, \fBRyleRadio\&.Tracks\&.ClipRadioTrack\&.Init()\fP, \fBRyleRadio\&.Tracks\&.ProceduralRadioTrack\&.Init()\fP, and \fBRyleRadio\&.Tracks\&.StationRadioTrack\&.NextTrack()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
