.TH "RyleRadio.Editor" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.Editor \- \fBEditor\fP scripts for classes and attributes, notably excluding \fBMultiselectAttribute\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRadioBroadcasterEditor\fP"
.br
.RI "Custom inspector for a \fBRadioBroadcaster\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&. "
.ti -1c
.RI "class \fBRadioDataEditor\fP"
.br
.RI "A custom editor for \fBRadioData\fP 
.br

.br
 This mainly exists so that we can reset tracks when they're newly added to the \fBRadioData\fP and prevent them from being linked- I don't think it actually does its job for that, though 
.br

.br
\fBSee: \fP\fBRadioData\fP\&. "
.ti -1c
.RI "class \fBRadioInsulatorEditor\fP"
.br
.RI "Custom inspector for a \fBRadioInsulator\fP 
.br

.br
This is mainly so that we can use \fRHandles\fP (draggable gizmos)\&. "
.ti -1c
.RI "class \fBStationRadioTrackEditor\fP"
.br
.RI "The editor for a \fBStationRadioTrack\fP 
.br

.br
This mainly exists so that we can reset any newly added tracks in the station- much the same as \fBRadioDataEditor\fP 
.br
\fBSee: \fP\fBStationRadioTrack\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBEditor\fP scripts for classes and attributes, notably excluding \fBMultiselectAttribute\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
