.TH "RyleRadio.MultiselectAttribute" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio.MultiselectAttribute \- A custom attribute that allows ints to display as a multiselect dropdown for a given collection, like a custom LayerMask\&. Due to int limitations you can only have up to 32 options\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiselectAttribute\fP (string _optionsName)"
.br
.RI "Initialises the attribute\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T[] \fBTo< T >\fP (int _flags, T[] _options)"
.br
.RI "Converts an int with the Multiselect attribute to a subset of a given list according to the int flags- converts the flag int to usable data\&. "
.ti -1c
.RI "static int[] \fBToInt\fP (int _flags)"
.br
.RI "Shorthand for \fRMultiselectAttribute\&.To<int>(_flags, _options)\fP\&. Useful for converting a multiselect to indexes in a list\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOptionsName\fP\fR [get, private set]\fP"
.br
.RI "Name of the variable this attribute uses for the options list\&. "
.ti -1c
.RI "static int[] \fBZeroTo31\fP\fR [get]\fP"
.br
.RI "A filler array with numbers 0 - 31, used when converting from a flag int to a list subset\&. "
.ti -1c
.RI "static int[] \fBOneTo32\fP\fR [get]\fP"
.br
.RI "A filler array with numbers 1 - 32\&. Not yet used, but theoretically helpful for indexing from the end of a list (list[^i] instead of list[i]) "
.in -1c
.SH "Detailed Description"
.PP 
A custom attribute that allows ints to display as a multiselect dropdown for a given collection, like a custom LayerMask\&. Due to int limitations you can only have up to 32 options\&. 

Has editor code in \fBMultiselectDrawer\fP 
.PP
Definition at line \fB21\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RyleRadio\&.MultiselectAttribute\&.MultiselectAttribute (string _optionsName)"

.PP
Initialises the attribute\&. 
.PP
Definition at line \fB55\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "T[] RyleRadio\&.MultiselectAttribute\&.To< T > (int _flags, T[] _options)\fR [static]\fP"

.PP
Converts an int with the Multiselect attribute to a subset of a given list according to the int flags- converts the flag int to usable data\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The eventType content of the list we're converting the flags to
.RE
.PP
\fBParameters\fP
.RS 4
\fI_flags\fP The int with the Multiselect attribute- a flag int
.br
\fI_options\fP The list we're getting a subset of according to the flags
.RE
.PP
\fBReturns\fP
.RS 4
A subset of \fR_options\fP that matches the \fR_flags\fP int
.RE
.PP

.PP
.PP
.nf
string[] options = new string[4] { "awesome", "attribute", "thanks", "ryle\-e" };

[Multiselect("options")]
private int flags1; // in the inspector, we set it to ["awesome", "thanks"]\- the first and third options in the inspector\&. this int then becomes 0x0101

public void Convert()
{
    int flags2 = 0x1010; // equivalent to selecting the second and fourth options in the inspector

    List<string> converted1 = Multiselect\&.To<string>(flags1, options); // sets to ["awesome", "thanks"]
    List<string> converted2 = Multiselect\&.To<string>(flags2, options); // sets to ["attribute", "ryle\-e"]
}
.fi
.PP

.PP
Definition at line \fB82\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.SS "int[] RyleRadio\&.MultiselectAttribute\&.ToInt (int _flags)\fR [static]\fP"

.PP
Shorthand for \fRMultiselectAttribute\&.To<int>(_flags, _options)\fP\&. Useful for converting a multiselect to indexes in a list\&. 
.PP
\fBParameters\fP
.RS 4
\fI_flags\fP The int with the Multiselect attribute
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB118\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.PP
Referenced by \fBRyleRadio\&.Components\&.Base\&.RadioComponentDataAccessor\&.AssignToTracksGeneric()\fP, and \fBRyleRadio\&.Components\&.Base\&.RadioOutputTrackAccessor\&.DoTrackAction()\fP\&.
.SH "Property Documentation"
.PP 
.SS "int [] RyleRadio\&.MultiselectAttribute\&.OneTo32\fR [static]\fP, \fR [get]\fP"

.PP
A filler array with numbers 1 - 32\&. Not yet used, but theoretically helpful for indexing from the end of a list (list[^i] instead of list[i]) 
.PP
Definition at line \fB43\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.SS "string RyleRadio\&.MultiselectAttribute\&.OptionsName\fR [get]\fP, \fR [private set]\fP"

.PP
Name of the variable this attribute uses for the options list\&. 
.PP
Definition at line \fB26\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.PP
Referenced by \fBMultiselectAttribute()\fP\&.
.SS "int [] RyleRadio\&.MultiselectAttribute\&.ZeroTo31\fR [static]\fP, \fR [get]\fP"

.PP
A filler array with numbers 0 - 31, used when converting from a flag int to a list subset\&. 
.PP
Definition at line \fB31\fP of file \fBMultiselectAttribute\&.cs\fP\&.
.PP
Referenced by \fBToInt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
