.TH "RyleRadio" 3 "Fri Oct 24 2025" "Version 1.0.0" "Ryle Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RyleRadio \- The entire package\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBComponents\fP"
.br
.RI "\fBComponents\fP to be placed on scene objects, e\&.g: Outputs, Broadcasters, Observers\&. "
.ti -1c
.RI "namespace \fBEditor\fP"
.br
.RI "\fBEditor\fP scripts for classes and attributes, notably excluding \fBMultiselectAttribute\fP\&. "
.ti -1c
.RI "namespace \fBTracks\fP"
.br
.RI "\fBTracks\fP to be used on a radio- includes base classes\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMultiselectAttribute\fP"
.br
.RI "A custom attribute that allows ints to display as a multiselect dropdown for a given collection, like a custom LayerMask\&. Due to int limitations you can only have up to 32 options\&. "
.ti -1c
.RI "class \fBMultiselectDrawer\fP"
.br
.RI "Draws the \fBMultiselectAttribute\fP in the inspector\&. "
.ti -1c
.RI "class \fBRadioData\fP"
.br
.RI "The central data object defining the radio\&. Contains the tracks and information required to play the radio at runtime\&. 
.br

.br
Has a custom editor at \fBRadioDataEditor\fP\&. "
.ti -1c
.RI "class \fBRadioUtils\fP"
.br
.RI "Various utilities used throughout the project\&. "
.in -1c
.SH "Detailed Description"
.PP 
The entire package\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Ryle Radio from the source code\&.
